// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsabczhfeehazuyajarx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzYWJjemhmZWVoYXp1eWFqYXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NjY2MTEsImV4cCI6MjA1ODE0MjYxMX0.UldOcr7qhvX6Wa77fGoB8pkHOgv8HulcMsX_zULttNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);